# Generated by Django 3.0.7 on 2020-10-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asadeye_api', '0002_auto_20201024_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
