# Generated by Django 3.0.7 on 2020-10-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asadeye_api', '0003_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
