# Generated by Django 3.0.7 on 2020-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asadeye_api', '0004_auto_20201024_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('path', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
