# Generated by Django 3.0.7 on 2020-10-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asadeye_api', '0005_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='name',
            new_name='image_name',
        ),
    ]
