# Generated by Django 3.0.7 on 2020-10-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asadeye_api', '0006_auto_20201024_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.FileField(default='some_path', upload_to='images/', verbose_name=''),
            preserve_default=False,
        ),
    ]
