# Generated by Django 3.0.7 on 2020-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asadeye_api', '0007_auto_20201024_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.FileField(upload_to='images/'),
        ),
    ]
