# Generated by Django 3.0.7 on 2020-10-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asadeye_api', '0009_images_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asadeye_api.Products'),
            preserve_default=False,
        ),
    ]
